build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"  
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  i386: "ghcr.io/home-assistant/i386-base:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: MCP Proxy"
  org.opencontainers.image.description: "Connect to MCP servers that run on SSE transport, or expose stdio servers as an SSE server"
  org.opencontainers.image.source: "https://github.com/YOUR_USERNAME/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2023.01.0"
